"""empty message

Revision ID: 52450f21cc87
Revises: 4944f7d753dc
Create Date: 2025-05-07 13:43:54.721026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52450f21cc87'
down_revision = '4944f7d753dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('comentario_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comentario_post_id_fkey', 'posts', ['post_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
